- gasometer/src/costs.rs
- gasometer/src/lib.rs
- runtime/src/lib.rs
- src/executor/stack/mod.rs
See https://eips.ethereum.org/EIPS/eip-3529
> London: EIP-3529

- core/src/eval/macros.rs
- core/src/eval/misc.rs
- core/src/eval/mod.rs
- core/src/memory.rs
- core/src/stack.rs
- gasometer/src/lib.rs
- runtime/src/eval/macros.rs
- runtime/src/eval/system.rs
H256 is [u8; 32]
U256 is [u64; 4]
According to EVM spec, when H256 is interpreted as a number, the byte
order is big endian. WASM, in contrast, uses little-endian
representation (the same used by CPUs internally).
Before this PR, evm stored operand stack as `Vec<H256>`, so any
arithmetic op entailed indianness conversion. As WASM lacks equivalent
to bswap instruction, this is a lot of work.
After this PR, stack is using U256 (so, little-endian in memory). This
is also reperesentation used by all of geth, evmone and odin.
For the uniswap benchmark, the before-after WASM (not total) gas cost is
110436615921984
90540800264244
Notes: 
* I've made this on top of https://github.com/rust-blockchain/evm/pull/97
* I think it also makes sense to rename macros further (`pop_u256` -> `pop`), such …
> switch vm stack to little endian representation 

- runtime/src/eval/mod.rs
- runtime/src/eval/system.rs
- runtime/src/interrupt.rs
- runtime/src/lib.rs
- src/executor/stack/executor.rs
- src/executor/stack/mod.rs
- src/executor/stack/tagged_runtime.rs
- src/lib.rs
- src/maybe_borrowed.rs
Duplicate of https://github.com/rust-blockchain/evm/pull/136 but for our fork (since we may get it reviewed and merged faster that way).
Related to https://github.com/aurora-is-near/aurora-engine/issues/627
> Fix: explicit EVM call stack

- src/executor/stack/executor.rs
The move to an explicit stack for EVM calls resulted in some of the tracing events not being emitted. This PR fixes the issue. Thanks to @last-las for bringing this issue to our attention!
At the same time I'm also fixing a couple little clippy warnings.
> Fix(tracing): include missing Exit events

- src/executor/stack/executor.rs
- src/tracing.rs
Currently in SputnikVM there is no way within the tracing mechanism to see what code was generated from a contract deploy. However, this functionality is necessary to fill in the `code` field in some tracing outputs (see https://docs.alchemy.com/reference/what-are-evm-traces#create ). In this PR I add a new event variant to capture the code stored when create executions happen.
> Feat(tracing): trace code stored as a result of create

- runtime/src/eval/system.rs
`returndatacopy` was missing proper handling of the `len == 0` case.
I reviewed all other instances of the `pop_usize` macro and it looks like they are protected by gas costs. Therefore I did not change anything else related to `pop_usize`.
> Fix panic in returndatacopy

- Cargo.toml
- src/executor/stack/executor.rs
The PR adds an additional `transact_create_fixed` function which allows to creation smart contract with a specified address.
> feat: add transact_create_fixed function

- .github/workflows/rust.yml
- core/src/error.rs
- core/src/eval/misc.rs
- core/src/eval/mod.rs
- core/src/lib.rs
- core/src/memory.rs
- core/src/opcode.rs
- core/src/stack.rs
- core/src/utils.rs
- core/src/valids.rs
- gasometer/src/costs.rs
- gasometer/src/lib.rs
- runtime/src/lib.rs
- src/backend/memory.rs
- src/executor/stack/executor.rs
- src/executor/stack/memory.rs
- src/executor/stack/precompile.rs
The PR applies suggestions by clippy levels `all` and `nursery`.
> chore: apply suggestions by clippy

- core/src/lib.rs
- runtime/src/eval/system.rs
- rust-toolchain.toml
I made a mistake in #26 by adding the early return when `len == 0`. The function is still supposed to return an error if the `data_offset` is out of bounds even if when `len` is zero. This was causing a failure in the `st_memory` EVM test.
I have modified the logic to simply assign `memory_offset` as 0 if `len == 0` instead of existing the function early. This assignment is safe because `memory_offset` is not actually used in any of the memory-related functions in the case `len` is zero.
All the EVM tests now once again pass.
> Fix(returndatacopy): Data offset out of bounds is still an error even if len==0

- .github/workflows/rust.yml
- core/Cargo.toml
- core/src/lib.rs
- gasometer/Cargo.toml
- runtime/Cargo.toml
The PR fixes compile error with the `no_std` feature.
> fix: use full path to vec macro

- src/executor/stack/executor.rs
The Shanghai fork enables a warming coinbase address feature which, aims to reduce the gas cost of accessing the coinbase address. At the start of transaction execution, `accessed_addresses` shall also be initialized to include the address returned by COINBASE. Before these changes, we only used the warming coinbase address in the `transact_call` function. The PR adds a warming coinbase address to the `transact_create`, `transact_create_fixed` and `transact_create2` functions.
> feat: warm coinbase address in create transactions

- evm-tests/ethcore-builtin/src/lib.rs
- evm-tests/jsontests/src/main.rs
- evm-tests/jsontests/src/state.rs
- src/executor/stack/executor.rs
- src/executor/stack/memory.rs
Fixed tests for `EIP-3860`.
↪️ Realted to Cancun implenentation PRs: #39 and #40
> Fix: tests for EIP-3860

- core/src/eval/misc.rs
- core/src/lib.rs
- core/src/memory.rs
- core/src/stack.rs
- core/src/utils.rs
- evm-tests/jsontests/src/state.rs
- gasometer/src/costs.rs
- runtime/src/eval/system.rs
- src/executor/stack/executor.rs
- src/executor/stack/memory.rs
- src/lib.rs
Added optimizations:
➡️  constants for `U256`: `U64_MAX`, `USIZE_MAX`
If was added cache for `Backend` operations.
➡️  added cache for operations with `Backend` trait for `MemoryStack`
But as result of testings for `aurora-engine` gas cost insignificantly increased (about `0.5%`) for 1 tests. And it was not gas decreased. So it was finally removed.
> Feat: add optimizations for U256 constant calculations and Backend operations

- core/src/error.rs
- core/src/eval/macros.rs
- core/src/eval/misc.rs
- core/src/lib.rs
- core/src/stack.rs
- runtime/src/eval/macros.rs
- runtime/src/eval/system.rs
During optimizations made in  PR #9 `Use usize rather than u256 for memory offsets` was removed usize check and made pure `U256 -> usize` (with panics on overflow).
It brings some kind of problems: NEAR smartcontracts fails when casting U256 overflow, and it mean sender didn't pay a gas fee.
This PR intends to estimate gas cost.
➡️ Refactored `usize` check for `USIZE_MAX`
➡️ Added a new type of errors for `usize` casting
⏫ Refactored `fn return_value` array reallocation logic (thanks for @aleksuss )
As behavior is changed when `U256` is cast to `usize` it introduces breaking changes, as for previous version expected behavior was panic, and with new changes, it just returns an error.
`wasm32` (NEAR Protocol) gas cost changes: https://github.com/aurora-is-near/aurora-engine/pull/933
➡️  As …
> Feat: add usize casting strict check

- .github/workflows/rust.yml
- Cargo.toml
- evm-tests/ethjson/src/spec/spec.rs
- evm-tests/jsontests/src/state.rs
Switched to [ethereum/tests v14.0](https://github.com/ethereum/tests/releases/tag/v14.0). Main changes: all tests for previous hard forks moved to `LegacyTests/Cancun/GeneralStateTests/`
➡️  Added `Prague` hard fork check for new tests compatibility: `Prague-Electra` (aka `Pectra`) is an upcoming hard fork
➡️  Extended errors message checking
➡️  Added CI tests (as all previous hard forks moved to `LegacyTests`): `LegacyTests/Cancun/GeneralStateTests/`
➡️  Added CI tests: `ethtests/EIPTests/StateTests/`
➡️  Updated CI to `ethereum/tests v14.0`
> Feat: ethereum tests v14.0

- core/src/error.rs
- core/src/eval/macros.rs
- core/src/eval/misc.rs
- runtime/src/eval/macros.rs
- runtime/src/eval/system.rs
Refactored EVM `ExitFatal` reason for only Fatal `cases`.
:arrow_right: Moved `ExitFatal::UsizeOverflow` to `ExitError::UsizeOverflow` as it's not `Fatal` case for EVM exit.
:arrow_backward:  Please **NOTE** that it can break compatibility, as was changed  EVM `ExitReason`.
> Chore: Refactore EVM ExitFatal reason

- Cargo.toml
- runtime/src/lib.rs
➡️  Fixed config hard fork function as `const fn`
For now, keeping functions as `const` with `from` or `try_form` transformation is impossible.
In that particular case, `unsigned -> signed` casting is safe for `EVM hard fork config functions`.
⚠️  `cons fn ` config functions is pretty helpful as EVM initialization.
> Feat: Fix config hard fork functions as const functions

- gasometer/src/lib.rs
- runtime/src/lib.rs
- src/executor/stack/executor.rs
- src/executor/stack/memory.rs
➡️ Executor - refactored `creation field` - removed as redundand.
➡️ `create_inner` - refactored warming address
➡️ Added documentation for `substate` exit logic
> Feat: Add documenattion and Executor refactoring

- .github/workflows/rust.yml
⏫  Updated https://github.com/ethereum/tests to `v14.1`
> Chore: Update eth-tests to v14.1

- evm-tests/ethjson/src/bytes.rs
- evm-tests/ethjson/src/spec/spec.rs
- evm-tests/ethjson/src/test_helpers/skip.rs
- evm-tests/jsontests/src/state.rs
- rust-toolchain.toml
- src/backend/memory.rs
- Updated toolchain to `Rust 1.81.0`
- Fixed clippy and formating according to new requirements
> Chore: update to Rust 1.81.0

- gasometer/src/lib.rs
- runtime/src/handler.rs
- src/executor/stack/executor.rs
- src/executor/stack/mod.rs
- src/executor/stack/precompile.rs
➡️  Refactored `IsPrecompileResult` type.
- Removed error relations
- Remove extra gas cost field
➡️ Refactored `is_cold` - return result without error
Due to the fact that `EVM Precompiles` cannot contain additional information about gas calculation for a warm address, there is no need for redundant fields in the `IsPrecompileResult` type. This situation is unreachable.
As a result, this allows us to completely eliminate error returns in the `is_cold` function, since it cannot return an error. Currently, there are no `Precompiles` that support warm address logic in their functionality and, at the same time, charge additional gas.
Thus, it is possible to simplify the `IsPrecompileResult` type without any issues, while making the `is_cold` mechanism non-error-returning.
**Important note:** …
> Feat: Refactore IsPrecompileResult type

- Cargo.toml
- runtime/src/eval/system.rs
- runtime/src/handler.rs
- src/executor/stack/executor.rs
Refactoring: `create_inner` and `gas_limi`t calculation.
> Feat: Refactore Executor

- Cargo.toml
- src/executor/stack/executor.rs
Added optimizations with `smallvec` crate. The intention is to reduce memory allocation when it possible.
One of the most significant problems for memory allocation and re-allocation is unknown size of data. To mitigate it, we can allocate on the stack for arrays, when size is known. And reallocate memory on the heap for program and algorithm needs. `smallvec` solves it good enough.
It was tested through `aurora-engine` tests. It shows insignificant NEAR gas consumption improvement.
As NEAR gas consumption improved insignificantly, I don't mind if there are some arguments against this solution.
> Feat: optimizations with `smallvec`

- Cargo.toml
- core/src/eval/macros.rs
- core/src/stack.rs
- evm-tests/EIP-152/src/lib.rs
- evm-tests/ethcore-builtin/Cargo.toml
- evm-tests/ethcore-builtin/src/lib.rs
- evm-tests/ethjson/Cargo.toml
- evm-tests/ethjson/src/lib.rs
- evm-tests/jsontests/Cargo.toml
- evm-tests/jsontests/src/state.rs
- evm-tests/jsontests/src/utils.rs
- evm-tests/jsontests/src/vm.rs
- runtime/src/eval/macros.rs
- runtime/src/eval/system.rs
- rust-toolchain.toml
- src/backend/mod.rs
- src/executor/stack/mod.rs
- src/maybe_borrowed.rs
⛓️ 🛋️  Updated:
➡️ Rust  toolchain `1.82.0` 
➡️ Refactored dependencies
- new version of `primitive-types`
- new version of `rlp`
- remover `ethereum` dependency as outdated and incompatible with the new version of `primitive-types`. Created new type `Log`.
> Feat: update toolchain and refactore dependencies

- .catalog-info.yaml
- core/.catalog-info.yaml
- gasometer/.catalog-info.yaml
- runtime/.catalog-info.yaml
PR takes care of adding [catalog descriptor files](https://backstage.io/docs/features/software-catalog/descriptor-format) that represent `sputnikvm` as a library for our software catalog.
> chore: add catalog entities

- evm-tests/EIP-152/src/portable.rs
- evm-tests/ethjson/src/bytes.rs
- evm-tests/ethjson/src/uint.rs
- fuzzer/src/main.rs
- gasometer/src/lib.rs
- rust-toolchain.toml
- src/backend/memory.rs
- src/executor/stack/executor.rs
- src/executor/stack/memory.rs
- src/maybe_borrowed.rs
➡️ Updated toolchain to `rust 1.84`
➡️ Fixed clippy warnings
> Chore: update to rust 1.84

- .github/workflows/rust.yml
- Cargo.toml
- evm-tests/EIP-152/src/portable.rs
- evm-tests/ethjson/src/bytes.rs
- evm-tests/ethjson/src/uint.rs
- evm-tests/jsontests/Cargo.toml
- evm-tests/jsontests/src/main.rs
- evm-tests/jsontests/src/state.rs
- evm-tests/jsontests/src/utils.rs
- fuzzer/src/main.rs
- gasometer/src/lib.rs
- runtime/src/eval/system.rs
- runtime/src/lib.rs
- rust-toolchain.toml
- src/backend/memory.rs
- src/executor/stack/executor.rs
- src/executor/stack/memory.rs
- src/maybe_borrowed.rs
After `ethereum-pectra-devnet-5` release, [ EIP-7702](https://eips.ethereum.org/EIPS/eip-7702) was changed.
This PR includes:
➡️ Gas cost changed
➡️ `EXTCODE*` behavior changed for designator
➡️ Added additional validation step.
> Feat: extend EIP-7702

- .github/workflows/rust.yml
⬆️ Updated CI `execution-spec-tests` to `pectra-devnet-5 v1.2.0`.
> Chore: update execution-spec-tests to pectra-devnet-5 v1.2.0

- .github/workflows/rust.yml
- evm-tests/jsontests/src/state.rs
- evm-tests/jsontests/src/utils.rs
- gasometer/src/lib.rs
- runtime/src/lib.rs
- src/executor/stack/executor.rs
➡️  Added [EIP-7623](https://eips.ethereum.org/EIPS/eip-7623) for Prague hard fork.
➡️  Extended tests for `EIP-7623`.
> Feat: add EIP-7623

- .github/workflows/rust.yml
- evm-tests/ethcore-builtin/src/lib.rs
- evm-tests/jsontests/Cargo.toml
- evm-tests/jsontests/src/state.rs
Created a tool for dumping test cases from `jsontests`. It dump relevant EVM state to reproduce it in `aurora-engine-tests`.
➡️ Added feature flag for dumping tool.
➡️ Related to: aurora-is-near/aurora-engine/pull/990
> Feat: Add state tests dump for jsottests

- .github/workflows/lint.yml
- .github/workflows/rust.yml
- README.md
- evm-tests/jsontests/src/main.rs
- evm-tests/jsontests/src/state.rs
➡️  Updated `ethereum/tests` to [v17.0](https://github.com/ethereum/tests/releases/tag/v17.0)
➡️  Added `file_name` to `assert` messages.
➡️  Changed CI: separated to `lint` and `ethtests`
➡️  Added additional badges to `README.md`
> Feat: update ethereum/tests to v17.0

- evm-tests/ethcore-builtin/src/lib.rs
- evm/src/backend/memory.rs
- evm/src/core/eval/mod.rs
- evm/src/core/mod.rs
- evm/src/executor/stack/executor.rs
- evm/src/executor/stack/memory.rs
- evm/src/gasometer/mod.rs
- evm/src/runtime/eval/system.rs
- evm/src/runtime/interrupt.rs
- rust-toolchain.toml
🚀  Rust toolchain updated to `v1.86`
➡️ Fixed clippy
> Chore: update rust toolchain to v1.86

- .github/workflows/rust.yml
➡️ Added latest [execution-spec-tests v4.4.0 (Stromovka)](https://github.com/ethereum/execution-spec-tests/releases/tag/v4.4.0)
➡️ Added new rule for CI
Due to the emergence of a new type of tests under version `fixtures-static-v4.4.0` related to `ethereum/tests` (actually static fixtures contains `GeneralStateTests` replicas), this has caused confusion regarding the test contents. For example, versions `ethereum/tests v17.0` contains different tests count. As a result, it was decided to keep the fixtures for `ethereum/tests` and add new tests in CI separately for `fixtures-static v4.4.0`, and to update future versions for both types of fixtures until the `execution-spec-tests` development team provides final clarification.
🛋️  As a result, the current number of covered tests is …
> Chore: add execution-spec-tests v4.4.0

- .github/workflows/rust.yml
➡️ Added latest [execution-spec-tests v4.5.0 (Hradčany)](https://github.com/ethereum/execution-spec-tests/releases/tag/v4.5.0)
🛋️  As a result, the current number of covered tests is **183,344**.
>  Chore: add execution-spec-tests v4.5.0

- Cargo.toml
- evm/src/core/memory.rs
- evm/src/core/stack.rs
- evm/src/core/valids.rs
- evm/src/gasometer/costs.rs
- evm/src/gasometer/mod.rs
➡️ Added clippy allowances for `const fn` for compatibility with `Rust v1.86`, since `aurora-engine` currently supports only `v1.86`.
➡️ Refactored EVM gas handling for cases without delegated gas computation for warm/cold addresses. This affects EXT-* and BALANCE opcodes. Since the gas module was moved to a separate location (from opcode execution), it led to code inconsistency and implicit gas calculation logic. This can _potentially_ cause hard-to-detect bugs due to the unified accessed address logic for both warm and cold accesses.
> Feat: gas cost refactoring for EXT-opcodes
